---
all:
  children:
    eks_nodes:
      hosts:
        # EKS nodes will be discovered dynamically via AWS plugin
      vars:
        ansible_user: ec2-user
        ansible_ssh_private_key_file: ~/.ssh/adaptivq-key.pem
        
    bastion:
      hosts:
        bastion-prod:
          ansible_host: bastion.adaptivq.com
          ansible_user: ec2-user
          
    local:
      hosts:
        localhost:
          ansible_connection: local
          ansible_python_interpreter: /usr/bin/python3

  vars:
    project_name: adaptivq
    aws_region: us-east-1
