---
- name: Setup Monitoring Stack (Prometheus + Grafana)
  hosts: localhost
  gather_facts: false
  
  vars:
    environment: "{{ lookup('env', 'ENVIRONMENT') | default('dev', true) }}"
    
  tasks:
    - name: Add Prometheus Helm repository
      kubernetes.core.helm_repository:
        name: prometheus-community
        repo_url: https://prometheus-community.github.io/helm-charts
    
    - name: Add Grafana Helm repository
      kubernetes.core.helm_repository:
        name: grafana
        repo_url: https://grafana.github.io/helm-charts
    
    - name: Create monitoring namespace
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: monitoring
    
    - name: Install Prometheus
      kubernetes.core.helm:
        name: prometheus
        chart_ref: prometheus-community/kube-prometheus-stack
        release_namespace: monitoring
        create_namespace: true
        values:
          prometheus:
            prometheusSpec:
              retention: 15d
              storageSpec:
                volumeClaimTemplate:
                  spec:
                    accessModes: ["ReadWriteOnce"]
                    resources:
                      requests:
                        storage: 50Gi
          grafana:
            enabled: true
            adminPassword: "{{ lookup('env', 'GRAFANA_ADMIN_PASSWORD') | default('admin', true) }}"
            persistence:
              enabled: true
              size: 10Gi
    
    - name: Display Grafana access information
      debug:
        msg: 
          - "Grafana is installed in the monitoring namespace"
          - "Access Grafana by port-forwarding: kubectl port-forward -n monitoring svc/prometheus-grafana 3000:80"
          - "Default credentials: admin / {{ lookup('env', 'GRAFANA_ADMIN_PASSWORD') | default('admin', true) }}"
