apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: adaptivq

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - postgres-statefulset.yaml
  - redis-statefulset.yaml
  - backend-deployment.yaml
  - celery-deployment.yaml
  - frontend-deployment.yaml
  - ingress.yaml
  - hpa.yaml

commonLabels:
  app.kubernetes.io/name: adaptivq
  app.kubernetes.io/managed-by: kustomize
